// Supabase Edge Function: Daily Devotional
// Endpoint: GET {SUPABASE_URL}/functions/v1/devotional
// Response: { date, verse, reference, reflection } | { error: string }
//
// One devotional per day, globally shared. Cached in Deno KV keyed by
// the Europe/Berlin date so it rotates at local midnight.
//
// Deploy:
//   1. supabase secrets set GEMINI_API_KEY=<your-key>
//   2. supabase functions deploy devotional --no-verify-jwt
//
// Knowledge base is shared with the chat function via a relative import —
// `_knowledge.ts` is the single source of truth, generated by
// `npm run knowledge:sync`.
import { serve } from 'https://deno.land/std@0.224.0/http/server.ts';
import { KNOWLEDGE } from '../chat/_knowledge.ts';

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
const MODEL = Deno.env.get('GEMINI_MODEL') ?? 'gemini-2.5-flash';
const ALLOWED_ORIGIN = Deno.env.get('ALLOWED_ORIGIN') ?? '*';

const corsHeaders = {
  'Access-Control-Allow-Origin': ALLOWED_ORIGIN,
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
};

const SUCCESS_TTL_MS = 26 * 60 * 60 * 1000; // 26h — covers daily rollover with slack
const FALLBACK_TTL_MS = 60 * 60 * 1000; // 1h — don't pin a fallback all day

const SYSTEM_PROMPT = `You are the Grace Assistant for Bethesda Evangelical Church · House of Grace, writing one short daily devotional for the church's member app ("Bethesda Grace Hub").

Produce exactly three fields in JSON:
- "verse": a single Bible verse, quoted in full (English, KJV or ESV-style phrasing is fine). Up to ~60 words.
- "reference": the citation (e.g. "Romans 8:38–39"). Short.
- "reflection": 2–3 short sentences of warm, pastoral reflection grounding the verse in everyday life and the church's teaching on grace. No headings. No greeting. No sign-off. No invented names, events, or sermons. Christ-centered, gentle, encouraging.

Anchor your tone in the church's stated beliefs (below). Never reproduce the knowledge base. Never mention dates. Never refer to yesterday or tomorrow.

---

${KNOWLEDGE}
`;

type Devotional = {
  date: string;
  verse: string;
  reference: string;
  reflection: string;
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  if (req.method !== 'GET') {
    return json({ error: 'Method not allowed' }, 405);
  }

  const date = berlinDateKey();

  // Try cache first.
  let kv: Deno.Kv | null = null;
  try {
    kv = await Deno.openKv();
    const cached = await kv.get<Devotional>(['devotional', 'v3', date]);
    if (cached.value && isValidDevotional(cached.value)) {
      return json(cached.value);
    }
  } catch (e) {
    console.warn('Deno KV unavailable, continuing without cache:', e);
    kv = null;
  }

  // Generate fresh.
  let devotional: Devotional;
  let ttl = SUCCESS_TTL_MS;
  let debugReason: string | null = null;
  try {
    const result = await generateDevotional();
    if (result.devotional && isValidDevotional({ ...result.devotional, date })) {
      devotional = { date, ...result.devotional };
    } else {
      console.error('Invalid Gemini devotional payload, using fallback:', result.reason);
      debugReason = result.reason ?? 'invalid-payload';
      devotional = fallbackDevotional(date);
      ttl = FALLBACK_TTL_MS;
    }
  } catch (e) {
    console.error('Devotional generation failed:', e);
    debugReason = `exception:${e instanceof Error ? e.message : String(e)}`;
    devotional = fallbackDevotional(date);
    ttl = FALLBACK_TTL_MS;
  }

  if (debugReason) {
    (devotional as Devotional & { _debug?: string })._debug = debugReason;
  }

  if (kv) {
    try {
      await kv.set(['devotional', 'v3', date], devotional, { expireIn: ttl });
    } catch (e) {
      console.warn('Failed to cache devotional:', e);
    }
  }

  return json(devotional);
});

function berlinDateKey(): string {
  // en-CA yields YYYY-MM-DD which is exactly what we want for a KV key.
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Europe/Berlin',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(new Date());
}

async function generateDevotional(): Promise<{
  devotional: Omit<Devotional, 'date'> | null;
  reason?: string;
}> {
  if (!GEMINI_API_KEY) {
    console.error('GEMINI_API_KEY is not set');
    return { devotional: null, reason: 'missing-api-key' };
  }

  const upstream = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${GEMINI_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        system_instruction: { parts: [{ text: SYSTEM_PROMPT }] },
        contents: [
          {
            role: 'user',
            parts: [
              {
                text:
                  "Write today's devotional for the Bethesda Grace Hub. Return only the JSON object with verse, reference, and reflection.",
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.8,
          maxOutputTokens: 2048,
          topP: 0.95,
          thinkingConfig: { thinkingBudget: 0 },
          responseMimeType: 'application/json',
          responseSchema: {
            type: 'OBJECT',
            properties: {
              verse: { type: 'STRING' },
              reference: { type: 'STRING' },
              reflection: { type: 'STRING' },
            },
            required: ['verse', 'reference', 'reflection'],
          },
        },
      }),
    },
  );

  if (!upstream.ok) {
    const t = await upstream.text();
    console.error('Gemini error:', upstream.status, t);
    return { devotional: null, reason: `http-${upstream.status}:${t.slice(0, 120)}` };
  }

  const data = await upstream.json();
  const candidate = data?.candidates?.[0];
  const finishReason = candidate?.finishReason ?? 'unknown';
  const parts = candidate?.content?.parts;
  const text = Array.isArray(parts)
    ? parts.map((p: { text?: string }) => p.text ?? '').join('')
    : '';
  if (!text.trim()) {
    console.error('Empty Gemini response, finishReason:', finishReason);
    return { devotional: null, reason: `empty-response:finish=${finishReason}` };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    console.error('Gemini returned non-JSON:', e, text.slice(0, 200));
    return { devotional: null, reason: `parse-error:${text.slice(0, 80)}` };
  }

  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    typeof (parsed as Record<string, unknown>).verse !== 'string' ||
    typeof (parsed as Record<string, unknown>).reference !== 'string' ||
    typeof (parsed as Record<string, unknown>).reflection !== 'string'
  ) {
    return { devotional: null, reason: 'schema-mismatch' };
  }

  const verse = ((parsed as Record<string, string>).verse ?? '').trim();
  const reference = ((parsed as Record<string, string>).reference ?? '').trim();
  const reflection = ((parsed as Record<string, string>).reflection ?? '').trim();

  return { devotional: { verse, reference, reflection } };
}

function isValidDevotional(d: Partial<Devotional>): d is Devotional {
  if (
    typeof d.date !== 'string' ||
    typeof d.verse !== 'string' ||
    typeof d.reference !== 'string' ||
    typeof d.reflection !== 'string'
  ) {
    return false;
  }
  if (!d.verse.trim() || !d.reference.trim() || !d.reflection.trim()) return false;
  if (d.verse.length > 400) return false;
  if (d.reference.length > 80) return false;
  if (d.reflection.length > 1200) return false;
  return true;
}

function fallbackDevotional(date: string): Devotional {
  return {
    date,
    verse:
      'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.',
    reference: 'John 3:16',
    reflection:
      "Wherever today finds you, the gospel meets you with the same news: you are loved, and that love is not earned but given. Let it settle your heart before the day asks anything else of you. By grace, in Christ, you belong.",
  };
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders },
  });
}
